---
# tasks file for coredns
- name: Download sha256 file for coredns
  get_url:
    url: https://github.com/coredns/coredns/releases/download/v{{ coredns_version }}/coredns_{{ coredns_version }}_{{ coredns_os }}_{{ coredns_arch }}.tgz.sha256
    dest: /tmp/coredns_{{ coredns_version }}_{{ coredns_os }}_{{ coredns_arch }}.tgz.sha256
    owner: "{{ coredns_owner }}"
    group: "{{ coredns_group }}"
    mode: 0444
  register: checksum_file
  delegate_to: localhost

- name: register sha256 checksum value for coredns
  set_fact:
    sha256_coredns: "{{ lookup('file', checksum_file['dest']).split(\t)[0] }}"
  delegate_to: localhost

- name: download coredns for linux
  get_url:
    url: https://github.com/coredns/coredns/releases/download/v{{ coredns_version }}/coredns_{{ coredns_version }}_{{ coredns_os }}_{{ coredns_arch }}.tgz
    dest: "/tmp"
    owner: "{{ coredns_owner }}"
    group: "{{ coredns_group }}"
    mode: 0655
    checksum: "sha256:{{ sha256_coredns }}"
  register: coredns
  delegate_to: localhost

- name: extract coredns
  unarchive:
    src: "{{ coredns['dest'] }}"
    dest: /tmp
    owner: "{{ coredns_owner }}"
    group: "{{ coredns_group }}"
    mode: 0655
  register: extracted_file
  delegate_to: localhost

- name: copy coredns to servers
  copy:
    src: "{{ extracted_file['dest'] }}"
    dest: "{{ coredns_bin_directory }}"
    owner: root
    group: root
    mode: 0655